"""Assemble the artifact page (dist/) and the web app's lesson module (docs/lessons.js) from src/."""
from pathlib import Path

root = Path(__file__).parent
src = root / "src"
page = (src / "shell.html").read_text()
script = (src / "lessons.js").read_text() + "\n" + (src / "runtime.js").read_text()
out = root / "dist" / "on-air-english.html"
out.parent.mkdir(exist_ok=True)
out.write_text(page + "<script>\n" + script + "</script>\n")
print(out, out.stat().st_size, "bytes")

# the web app (docs/, GitHub Pages) imports the same lesson data as an ES module
web = root / "docs" / "lessons.js"
web.write_text("// Generated by build.py from src/lessons.js. Edit the source, not this file.\n"
               + (src / "lessons.js").read_text() + "\nexport { STAGES, TOPICS };\n")
print(web)
