const STAGES = [
  { id: "warm",    name: "Разминка",           sec: 180,
    ru: "Лёгкий разговор о вашем дне. Отвечайте просто, одним-тремя предложениями.",
    goal: "Easy small talk: the learner's day, week, plans. Ask short, concrete questions that are easy to answer (e.g. 'What did you do this morning?'), one at a time. If there are phrases from the last lesson, ask questions that invite them naturally." },
  { id: "phrases", name: "Фразы урока",         sec: 180,
    ru: "Алекс даёт фразу — скажите с ней своё предложение.",
    goal: "Introduce today's target phrases ONE AT A TIME. Say the phrase, give a one-line example about the learner's life, then ask them to say their own sentence with it. React briefly: praise if natural, otherwise say the natural version and move on. Set done=true after the learner has tried all phrases." },
  { id: "talk",    name: "Разговор",           sec: 420,
    ru: "Обсуждаем тему урока: отвечайте на вопросы, высказывайте мнение.",
    goal: "A back-and-forth discussion on today's topic, like two colleagues over coffee. Ask one short, concrete question at a time, react to the answer, share your own view in one sentence, then ask a follow-up ('Why?', 'Can you give an example?', 'What about you?'). Never ask the learner to talk at length or give a speech. Do NOT correct out loud unless the meaning is unclear; log problems in notes instead." },
  { id: "role",    name: "Ситуация",           sec: 240,
    ru: "Ролевая игра: Алекс играет роль, вы отвечаете как в жизни.",
    goal: "Role-play the situation described below. First say in one sentence who you are and what the situation is, then speak in the role with short lines. Add a small complication so the learner has to negotiate or explain. Do NOT correct out loud; log problems in notes." },
  { id: "fix",     name: "Работа над ошибками", sec: 180,
    ru: "Алекс напомнит ваши ошибки — повторите эти фразы правильно.",
    goal: "Take up to three of today's logged mistakes one by one. Say: 'Earlier you said ...' then ask the learner to say it again in a more natural way. Confirm or give the natural version and ask them to repeat it once. Set done=true when all are covered (or if there were no mistakes, after one short free exchange)." }
];

const TOPICS = [
  { t: "Who I am & what I do", ru: "О себе и работе", talk: "the learner's job in IT, what a typical day looks like, what they like and dislike about it",
    role: "You are a friendly stranger at a tech conference coffee break. You ask what they do and want to understand it, but you are not from IT.",
    phrases: [["Basically, I work on…", "По сути, я занимаюсь…"], ["The main thing I do is…", "Главное, что я делаю, —…"], ["Long story short, …", "Короче говоря, …"]] },
  { t: "AI and the future of work", ru: "ИИ и будущее профессий", talk: "how AI changes jobs, which jobs disappear, whether AI is a threat or an opportunity for the learner",
    role: "You are a sceptical manager who thinks AI is overhyped. The learner has to convince you to try an AI tool in your team.",
    phrases: [["The way I see it, …", "Как я это вижу, …"], ["The thing is, …", "Дело в том, что…"], ["On the other hand, …", "С другой стороны, …"]] },
  { t: "Travel stories", ru: "Истории из путешествий", talk: "the learner's best and worst trips, what went wrong, places that surprised them",
    role: "You are a hotel receptionist. The learner arrives late at night and the booking is missing. They need a room.",
    phrases: [["It turned out that…", "Оказалось, что…"], ["And then, out of nowhere, …", "И тут внезапно…"], ["In the end, …", "В итоге…"]] },
  { t: "Running & tracking yourself", ru: "Бег и данные о себе", talk: "running, training, wearables, sleep and heart-rate data, motivation on bad days",
    role: "You are a beginner who wants to start running. Ask the learner lots of practical questions and push back on anything that sounds too hard.",
    phrases: [["The key is to…", "Главное — это…"], ["It makes a huge difference.", "Это очень сильно влияет."], ["It took me a while to figure out that…", "Мне понадобилось время, чтобы понять, что…"]] },
  { t: "The future of humanity", ru: "Будущее человечества", talk: "life in 2050, the biggest risks and hopes for humanity, living longer",
    role: "You are a journalist interviewing the learner for a podcast about the future. Ask short sharp questions and follow-ups.",
    phrases: [["Chances are, …", "Скорее всего, …"], ["It's hard to say, but…", "Сложно сказать, но…"], ["In the long run, …", "В долгосрочной перспективе…"]] },
  { t: "Tech I love and hate", ru: "Техника: любимая и бесячая", talk: "gadgets and apps the learner uses daily, what is overrated, what they wish existed",
    role: "You are a shop assistant trying to upsell an expensive gadget the learner does not need. They must politely refuse and explain what they actually want.",
    phrases: [["It's way better than…", "Это намного лучше, чем…"], ["What drives me crazy is…", "Что меня бесит, так это…"], ["The only downside is…", "Единственный минус —…"]] },
  { t: "Remote vs office", ru: "Удалёнка или офис", talk: "remote work vs office, four-day week, trust in teams, the learner's ideal setup",
    role: "You are the learner's boss who wants everyone back in the office five days a week. The learner negotiates for remote days.",
    phrases: [["I see your point, but…", "Понимаю вашу мысль, но…"], ["That's a fair point.", "Справедливо."], ["Let me push back on that a bit.", "Позвольте немного возразить."]] },
  { t: "Space & Mars", ru: "Космос и Марс", talk: "space exploration, Mars, whether it is worth the money, life on other planets",
    role: "You are a curious ten-year-old. Ask the learner simple but tricky 'why' questions about going to Mars.",
    phrases: [["In simple terms, …", "Проще говоря, …"], ["Imagine that…", "Представь, что…"], ["What most people don't realize is…", "Чего многие не понимают, так это…"]] },
  { t: "Business trips", ru: "Командировки и аэропорты", talk: "business travel, staying productive on the road, jet lag, airports and hotels",
    role: "You are an airline agent. The learner's flight is cancelled and they must get home tonight. Only expensive or inconvenient options exist at first.",
    phrases: [["Is there any way to…?", "Есть ли возможность…?"], ["I was wondering if…", "Хотел(а) узнать, можно ли…"], ["Just to make sure, …", "Просто чтобы уточнить, …"]] },
  { t: "Cities of the future", ru: "Города будущего", talk: "what makes a city great, self-driving cars, how cities will change in 20 years",
    role: "You are a city mayor at a public meeting. The learner proposes one big change for the city and you question the cost.",
    phrases: [["It would be great if…", "Было бы здорово, если бы…"], ["Compared to…, …", "По сравнению с…, …"], ["The problem with … is…", "Проблема с … в том, что…"]] },
  { t: "Longevity & health tech", ru: "Долголетие и технологии здоровья", talk: "living longer, biohacking, health data, AI doctors, habits that really work",
    role: "You are a salesperson for an expensive 'longevity' supplement. The learner is sceptical and asks for evidence.",
    phrases: [["If I could…, I'd…", "Если бы я мог(ла)…, я бы…"], ["I'm a bit skeptical about…", "Я скептически отношусь к…"], ["It's worth it if…", "Это того стоит, если…"]] },
  { t: "AI ethics", ru: "Этика ИИ", talk: "who is responsible for AI mistakes, privacy, rules for AI, AI and creativity",
    role: "You are on a panel discussion and take the opposite view to whatever the learner says about AI regulation.",
    phrases: [["That's a good question.", "Хороший вопрос."], ["Let me think about that for a sec.", "Дайте секунду подумать."], ["What I mean is…", "Я имею в виду, что…"]] },
  { t: "Pitch an idea", ru: "Питч своей идеи", talk: "startup ideas, problems worth solving, what makes a product successful",
    role: "You are an investor. The learner pitches a startup idea in one minute; then you ask tough questions about customers and money.",
    phrases: [["The problem is that…", "Проблема в том, что…"], ["Unlike…, we…", "В отличие от…, мы…"], ["The next step is…", "Следующий шаг —…"]] },
  { t: "Free talk", ru: "Свободный разговор", talk: "anything: jump between AI, travel, running, the future; practise switching topics naturally",
    role: "You are a new colleague at a team dinner. Keep the small talk going and change topics several times.",
    phrases: [["Speaking of…, …", "Кстати о…, …"], ["That reminds me of…", "Это напоминает мне…"], ["Going back to what you said…", "Возвращаясь к тому, что ты сказал(а)…"]] }
];

